/**
 * agent-runner — MVP executor for the ServiceManager.AI Engineering Agent.
 *
 * Loop: login → poll GET /agent-tasks → pick first NEW → claim (IN_PROGRESS)
 *       → read-only Ollama analysis → PATCH result (redacted) → DONE/FAILED.
 *
 * Safety:
 *   - Default mode is dry-run. Live mutations require an explicit --live flag.
 *   - Base URL is allowlisted; production hosts are refused.
 *   - Reads configuration from process.env only (never a .env file).
 *   - Read-only: no shell, no filesystem writes, no repository access.
 */

import { loadConfig, secretValues, type Config } from './config'
import { SmaClient, type AgentTask } from './smaClient'
import { runAnalysis } from './executor'
import { redact } from './redact'

function mask(value: string): string {
  if (!value) return '(unset)'
  if (value.length <= 4) return '****'
  return value.slice(0, 2) + '***' + value.slice(-2)
}

function log(msg: string): void {
  console.log(`[agent-runner] ${msg}`)
}

function printPlan(config: Config, missing: string[], baseUrlReason: string): void {
  log('--- configuration ---')
  log(`mode:            ${config.mode}`)
  log(`once:            ${config.once}`)
  log(`apiBaseUrl:      ${config.apiBaseUrl || '(unset)'}  [${baseUrlReason}]`)
  log(`agentEmail:      ${config.agentEmail || '(unset)'}`)
  log(`agentPassword:   ${mask(config.agentPassword)}`)
  log(`ollamaBaseUrl:   ${config.ollamaBaseUrl || '(unset)'}`)
  log(`ollamaModel:     ${config.ollamaModel || '(unset)'}`)
  log(`pollIntervalMs:  ${config.pollIntervalMs}`)
  log(`taskTimeoutMs:   ${config.taskTimeoutMs}`)
  if (missing.length) log(`missing env:     ${missing.join(', ')}`)
  log('--- planned steps (per task) ---')
  log('1. POST /auth/login                       -> cache JWT')
  log('2. GET  /agent-tasks                       -> find first status=NEW')
  log('3. PATCH /agent-tasks/:id/status {IN_PROGRESS}')
  log('4. read-only Ollama analysis of task.prompt (local model)')
  log('5. PATCH /agent-tasks/:id/result {redacted text}')
  log('6. PATCH /agent-tasks/:id/status {DONE | FAILED}')
}

async function processOne(client: SmaClient, config: Config, task: AgentTask): Promise<void> {
  const secrets = secretValues(config)
  log(`claiming task ${task.id} ("${task.title}")`)
  await client.setStatus(task.id, 'IN_PROGRESS')

  try {
    const result = await runAnalysis(config, task)
    const footer = `\n\n---\n_generated by agent-runner (read-only) · model: ${result.model}_`
    const safe = redact(result.text + footer, secrets)
    await client.setResult(task.id, safe)
    await client.setStatus(task.id, 'DONE')
    log(`task ${task.id} -> DONE`)
  } catch (err: any) {
    const message = redact(`Execution failed: ${err?.message || String(err)}`, secrets)
    try {
      await client.setResult(task.id, message)
      await client.setStatus(task.id, 'FAILED')
      log(`task ${task.id} -> FAILED (${err?.message || 'error'})`)
    } catch (reportErr: any) {
      log(`task ${task.id}: could not report failure: ${reportErr?.message || reportErr}`)
    }
  }
}

async function liveLoop(config: Config): Promise<void> {
  const client = new SmaClient(config)
  await client.login()
  log('authenticated')

  let stopping = false
  process.on('SIGINT', () => {
    log('SIGINT received — finishing current cycle then exiting')
    stopping = true
  })

  do {
    try {
      const tasks = await client.listTasks()
      const next = tasks
        .filter((t) => t.status === 'NEW')
        .sort((a, b) => a.createdAt.localeCompare(b.createdAt))[0]

      if (next) {
        await processOne(client, config, next)
      } else {
        log('no NEW tasks')
      }
    } catch (err: any) {
      log(`cycle error: ${err?.message || err}`)
    }

    if (config.once || stopping) break
    await new Promise((r) => setTimeout(r, config.pollIntervalMs))
  } while (!stopping)
}

async function main(): Promise<void> {
  const { config, missing, baseUrlAllowed, baseUrlReason } = loadConfig(process.argv.slice(2))

  printPlan(config, missing, baseUrlReason)

  if (config.mode === 'dry-run') {
    log('dry-run: no network calls, no task mutations performed. Use --live to run for real.')
    return
  }

  // live mode hard preconditions
  if (!baseUrlAllowed) {
    log(`refusing to run live: ${baseUrlReason}`)
    process.exitCode = 1
    return
  }
  if (missing.length) {
    log(`refusing to run live: missing required env: ${missing.join(', ')}`)
    process.exitCode = 1
    return
  }

  log('LIVE mode')
  await liveLoop(config)
}

main().catch((err) => {
  console.error(`[agent-runner] fatal: ${err?.message || err}`)
  process.exitCode = 1
})
