ALTER TABLE "Company"
ADD COLUMN IF NOT EXISTS "brandName" TEXT,
ADD COLUMN IF NOT EXISTS "legalName" TEXT,
ADD COLUMN IF NOT EXISTS "address" TEXT,
ADD COLUMN IF NOT EXISTS "phone" TEXT,
ADD COLUMN IF NOT EXISTS "email" TEXT,
ADD COLUMN IF NOT EXISTS "taxId" TEXT,
ADD COLUMN IF NOT EXISTS "registrationNumber" TEXT,
ADD COLUMN IF NOT EXISTS "logoUrl" TEXT,
ADD COLUMN IF NOT EXISTS "signatureLineName" TEXT,
ADD COLUMN IF NOT EXISTS "signatureLineTitle" TEXT;

ALTER TABLE "InspectionRun"
ADD COLUMN IF NOT EXISTS "reportNumber" TEXT,
ADD COLUMN IF NOT EXISTS "reportDate" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "documentTitle" TEXT DEFAULT 'Work Act';

CREATE INDEX IF NOT EXISTS "InspectionRun_reportNumber_idx"
ON "InspectionRun"("reportNumber");
