-- Align RolePermission rows with the accepted RC PBAC matrix.
-- This intentionally leaves PermissionBlock catalog rows intact and removes
-- only role-level grants that are outside backend/src/common/permissions-matrix.ts.

WITH expected(role_name, company_type_name, code) AS (
  VALUES
    ('PLATFORM_ADMIN', '*', 'TICKETS_VIEW'),
    ('PLATFORM_ADMIN', '*', 'LOCATIONS_VIEW'),
    ('PLATFORM_ADMIN', '*', 'USERS_MANAGE'),
    ('PLATFORM_ADMIN', '*', 'ANALYTICS_VIEW'),
    ('PLATFORM_ADMIN', '*', 'WORKFORCE_VIEW'),

    ('STAFF', '*', 'TICKETS_VIEW'),

    ('ADMIN', 'CLIENT', 'TICKETS_VIEW'),
    ('ADMIN', 'CLIENT', 'TICKETS_CREATE'),
    ('ADMIN', 'CLIENT', 'TICKETS_EDIT'),
    ('ADMIN', 'CLIENT', 'LOCATIONS_VIEW'),
    ('ADMIN', 'CLIENT', 'LOCATIONS_MANAGE'),
    ('ADMIN', 'CLIENT', 'USERS_MANAGE'),
    ('ADMIN', 'CLIENT', 'ANALYTICS_VIEW'),
    ('ADMIN', 'CLIENT', 'COMPANY_SETTINGS_EDIT'),
    ('ADMIN', 'CLIENT', 'WORKFORCE_SHIFT_USE'),
    ('ADMIN', 'CLIENT', 'WORKFORCE_VIEW'),

    ('ADMIN', 'PROVIDER', 'TICKETS_VIEW'),
    ('ADMIN', 'PROVIDER', 'TICKETS_CREATE'),
    ('ADMIN', 'PROVIDER', 'TICKETS_VIEW_AVAILABLE'),
    ('ADMIN', 'PROVIDER', 'TICKETS_EDIT'),
    ('ADMIN', 'PROVIDER', 'TICKETS_ASSIGN'),
    ('ADMIN', 'PROVIDER', 'TICKETS_CLAIM'),
    ('ADMIN', 'PROVIDER', 'TICKETS_STATUS_CHANGE'),
    ('ADMIN', 'PROVIDER', 'LOCATIONS_VIEW'),
    ('ADMIN', 'PROVIDER', 'LOCATIONS_MANAGE'),
    ('ADMIN', 'PROVIDER', 'USERS_MANAGE'),
    ('ADMIN', 'PROVIDER', 'ANALYTICS_VIEW'),
    ('ADMIN', 'PROVIDER', 'WORKFORCE_SHIFT_USE'),
    ('ADMIN', 'PROVIDER', 'WORKFORCE_VIEW'),
    ('ADMIN', 'PROVIDER', 'COMPANY_SETTINGS_EDIT'),

    ('MASTER', 'PROVIDER', 'TICKETS_VIEW'),
    ('MASTER', 'PROVIDER', 'TICKETS_CREATE'),
    ('MASTER', 'PROVIDER', 'TICKETS_VIEW_AVAILABLE'),
    ('MASTER', 'PROVIDER', 'TICKETS_EDIT'),
    ('MASTER', 'PROVIDER', 'TICKETS_ASSIGN'),
    ('MASTER', 'PROVIDER', 'TICKETS_CLAIM'),
    ('MASTER', 'PROVIDER', 'TICKETS_STATUS_CHANGE'),
    ('MASTER', 'PROVIDER', 'LOCATIONS_VIEW'),
    ('MASTER', 'PROVIDER', 'LOCATIONS_MANAGE'),
    ('MASTER', 'PROVIDER', 'USERS_MANAGE'),
    ('MASTER', 'PROVIDER', 'ANALYTICS_VIEW'),
    ('MASTER', 'PROVIDER', 'WORKFORCE_SHIFT_USE'),
    ('MASTER', 'PROVIDER', 'WORKFORCE_VIEW'),

    ('DISPATCHER', 'PROVIDER', 'TICKETS_VIEW'),
    ('DISPATCHER', 'PROVIDER', 'TICKETS_CREATE'),
    ('DISPATCHER', 'PROVIDER', 'TICKETS_VIEW_AVAILABLE'),
    ('DISPATCHER', 'PROVIDER', 'TICKETS_EDIT'),
    ('DISPATCHER', 'PROVIDER', 'TICKETS_ASSIGN'),
    ('DISPATCHER', 'PROVIDER', 'TICKETS_CLAIM'),
    ('DISPATCHER', 'PROVIDER', 'TICKETS_STATUS_CHANGE'),
    ('DISPATCHER', 'PROVIDER', 'LOCATIONS_VIEW'),
    ('DISPATCHER', 'PROVIDER', 'WORKFORCE_SHIFT_USE'),
    ('DISPATCHER', 'PROVIDER', 'LOCATIONS_MANAGE'),
    ('DISPATCHER', 'PROVIDER', 'USERS_MANAGE'),
    ('DISPATCHER', 'PROVIDER', 'ANALYTICS_VIEW'),
    ('DISPATCHER', 'PROVIDER', 'WORKFORCE_VIEW'),

    ('TECHNICIAN', 'PROVIDER', 'TICKETS_VIEW'),
    ('TECHNICIAN', 'PROVIDER', 'TICKETS_CREATE'),
    ('TECHNICIAN', 'PROVIDER', 'TICKETS_VIEW_AVAILABLE'),
    ('TECHNICIAN', 'PROVIDER', 'TICKETS_CLAIM'),
    ('TECHNICIAN', 'PROVIDER', 'TICKETS_STATUS_CHANGE'),
    ('TECHNICIAN', 'PROVIDER', 'LOCATIONS_VIEW'),
    ('TECHNICIAN', 'PROVIDER', 'WORKFORCE_SHIFT_USE'),

    ('NETWORK_DIRECTOR', 'CLIENT', 'TICKETS_VIEW'),
    ('NETWORK_DIRECTOR', 'CLIENT', 'TICKETS_CREATE'),
    ('NETWORK_DIRECTOR', 'CLIENT', 'TICKETS_EDIT'),
    ('NETWORK_DIRECTOR', 'CLIENT', 'LOCATIONS_VIEW'),
    ('NETWORK_DIRECTOR', 'CLIENT', 'USERS_MANAGE'),
    ('NETWORK_DIRECTOR', 'CLIENT', 'ANALYTICS_VIEW'),
    ('NETWORK_DIRECTOR', 'CLIENT', 'WORKFORCE_VIEW'),

    ('TERRITORIAL_MANAGER', 'CLIENT', 'TICKETS_VIEW'),
    ('TERRITORIAL_MANAGER', 'CLIENT', 'TICKETS_CREATE'),
    ('TERRITORIAL_MANAGER', 'CLIENT', 'TICKETS_EDIT'),
    ('TERRITORIAL_MANAGER', 'CLIENT', 'LOCATIONS_VIEW'),
    ('TERRITORIAL_MANAGER', 'CLIENT', 'WORKFORCE_VIEW'),

    ('CLIENT', 'CLIENT', 'TICKETS_VIEW'),
    ('CLIENT', 'CLIENT', 'TICKETS_CREATE'),
    ('CLIENT', 'CLIENT', 'TICKETS_EDIT'),
    ('CLIENT', 'CLIENT', 'LOCATIONS_VIEW')
),
obsolete AS (
  SELECT rp.id
  FROM "RolePermission" rp
  JOIN "PermissionBlock" pb ON pb.id = rp."permissionBlockId"
  WHERE NOT EXISTS (
    SELECT 1
    FROM expected e
    WHERE e.role_name = rp.role::text
      AND e.company_type_name = COALESCE(rp."companyType"::text, '*')
      AND e.code = pb.code
  )
)
DELETE FROM "RolePermission" rp
USING obsolete
WHERE rp.id = obsolete.id;
