/** Auto-generated focus-area Russian overrides for build-ru.ts */
export const FOCUS_LOCALIZATION_RU: Record<string, string> = {
  'canvasEngine.connectionTypes.chat': "Чат",
  'canvasEngine.connectionTypes.execution': "Execution",
  'canvasEngine.connectionTypes.runtime': "Runtime",
  'canvasEngine.layerLabels.projects': "Проекты",
  'canvasEngine.layerLabels.runtime': "Runtime",
  'canvasEngine.miniMapAria': "Мини-карта",
  'canvasEngine.modes.live': "Live",
  'canvasEngine.modes.runtime': "Runtime",
  'canvasEngine.nodeKinds.project': "Проект",
  'canvasEngine.nodeKinds.runtime': "Runtime",
  'canvasEngine.nodes': "узлов",
  'canvasEngine.openNode': "Открыть",
  'canvasEngine.runningTasks': "Задачи в работе",
  'canvasEngine.waitingApprovals': "Ожидающие согласования",
  'commandCenter.approvalsApproved': "одобрено",
  'commandCenter.brief.allClear': "Inbox пуст",
  'commandCenter.brief.approvalsHighlight': "{count} согласований ждут вашего решения",
  'commandCenter.brief.calmDay': "Операции стабильны — срочных блокеров не обнаружено",
  'commandCenter.brief.healthScore': "Индекс здоровья",
  'commandCenter.brief.openTimeline': "Открыть live timeline",
  'commandCenter.brief.projectHighlight': "AI Photo Lab на {progress}% к MVP",
  'commandCenter.brief.riskAlerts': "{count} критических алертов требуют внимания",
  'commandCenter.brief.riskWaiting': "{count} сотрудников заблокированы на согласовании",
  'commandCenter.brief.sprintHighlight': "Здоровье спринта: {health}",
  'commandCenter.brief.summary': "Ваш company pulse на сегодня — что движется, что требует вас и где сосредоточен риск.",
  'commandCenter.brief.unread': "{count} непрочитанных уведомлений",
  'commandCenter.brief.workingHighlight': "{count} сотрудников активно работают прямо сейчас",
  'commandCenter.canvasApprovals': "согласований",
  'commandCenter.canvasEmployees': "сотрудников",
  'commandCenter.canvasRuns': "запусков runtime",
  'commandCenter.canvasTasks': "активных задач",
  'commandCenter.charts.execution': "Execution",
  'commandCenter.charts.productivity': "Продуктивность",
  'commandCenter.controlRoomApprovals': "решений",
  'commandCenter.controlRoomWorking': "в работе",
  'commandCenter.description': "Операционный обзор — здоровье компании, команда, спринт, решения, риски и live-активность.",
  'commandCenter.empty.approvals': "Нет ожидающих согласований",
  'commandCenter.empty.canvas': "Граф Canvas недоступен",
  'commandCenter.empty.canvasTasks': "Нет активных задач на Canvas",
  'commandCenter.empty.controlRoom': "Снимок Control Room недоступен",
  'commandCenter.empty.reports': "Отчёты пока не созданы",
  'commandCenter.empty.runtime': "Запусков runtime пока нет",
  'commandCenter.empty.sprint': "Активный спринт не настроен",
  'commandCenter.empty.tools': "Запусков инструментов пока нет",
  'commandCenter.greeting.afternoon': "Добрый день, Owner.",
  'commandCenter.greeting.evening': "Добрый вечер, Owner.",
  'commandCenter.greeting.morning': "Доброе утро, Owner.",
  'commandCenter.healthScoreLabel': "индекс здоровья компании",
  'commandCenter.providerHealth.degraded': "Деградация",
  'commandCenter.providerHealth.up': "Исправно",
  'commandCenter.quickLaunch.atlas': "Atlas",
  'commandCenter.quickLaunch.canvas': "Canvas",
  'commandCenter.quickLaunch.controlRoom': "Control Room",
  'commandCenter.quickLaunch.handoffs': "Handoffs",
  'commandCenter.quickLaunch.kickoff': "Kickoff",
  'commandCenter.quickLaunch.max': "MAX",
  'commandCenter.quickLaunch.runtime': "Runtime",
  'commandCenter.quickLaunch.sprint': "Спринт",
  'commandCenter.runtimeWaiting': "ожидает согласования",
  'commandCenter.sections.canvasPreview': "Превью Canvas",
  'commandCenter.sections.charts': "Графики execution",
  'commandCenter.sections.controlRoomPreview': "Превью Control Room",
  'commandCenter.sections.employeesWorking': "Работающие сотрудники",
  'commandCenter.sections.liveTimeline': "Live-лента",
  'commandCenter.sections.notifications': "Уведомления",
  'commandCenter.sections.quickLaunch': "Быстрый запуск",
  'commandCenter.sections.recentReports': "Недавние отчёты",
  'commandCenter.sections.runtime': "Runtime",
  'commandCenter.sections.todaysSprint': "Спринт на сегодня",
  'commandCenter.sections.toolUsage': "Использование инструментов",
  'commandCenter.sprintHealth.at_risk': "под риском",
  'commandCenter.sprintHealth.on_track': "по плану",
  'commandCenter.sprintPoints': "story points",
  'commandCenter.sprintTasks': "задач выполнено",
  'commandCenter.title': "Командный центр",
  'commandCenter.toolCompleted': "завершено",
  'commandCenter.toolPending': "ожидает согласования",
  'common.notAvailable': "н/д",
  'common.selected': "Выбрано",
  'employeeProfile.sections.learning': "Обучение",
  'employeeProfile.sections.presence': "Presence",
  'employeeProfile.sections.runtime': "Runtime",
  'employeeWorkspace.actions.openChat': "Открыть чат",
  'employeeWorkspace.actions.openKnowledge': "Открыть Knowledge",
  'employeeWorkspace.actions.openRuntime': "Открыть Runtime",
  'employeeWorkspace.actions.openTask': "Открыть задачу",
  'employeeWorkspace.actions.startWork': "Начать работу",
  'employeeWorkspace.agenda.handoff': "Handoff",
  'employeeWorkspace.empty.approvals': "Нет ожидающих согласований.",
  'employeeWorkspace.empty.chats': "Чатов с этим сотрудником пока нет.",
  'employeeWorkspace.empty.currentRun': "Нет активного runtime run.",
  'employeeWorkspace.empty.knowledge': "Назначений knowledge пока нет.",
  'employeeWorkspace.empty.notifications': "Уведомлений для этого сотрудника нет.",
  'employeeWorkspace.empty.reports': "Этот сотрудник пока не создал отчётов.",
  'employeeWorkspace.empty.tasks': "Нет назначенных открытых delivery-задач.",
  'employeeWorkspace.empty.today': "На сегодня пока ничего не запланировано.",
  'employeeWorkspace.fields.currentFocus': "Текущий фокус",
  'employeeWorkspace.fields.openTasks': "Открытые задачи",
  'employeeWorkspace.fields.pendingDecisions': "Ожидающие решения",
  'employeeWorkspace.fields.workingOn': "Работает над",
  'employeeWorkspace.localOnly': "Агрегировано локально из tasks, executions, runtime runs, handoffs, knowledge, отчётов, чатов и events.",
  'employeeWorkspace.noCurrentFocus': "Нет активного фокуса",
  'employeeWorkspace.notFoundDescription': "Сотрудник не существует или не удалось загрузить snapshot workspace.",
  'employeeWorkspace.notFoundTitle': "Workspace сотрудника не найден",
  'employeeWorkspace.openApprovals': "Все согласования",
  'employeeWorkspace.openChat': "Открыть чат",
  'employeeWorkspace.openExecution': "Очередь execution",
  'employeeWorkspace.openKnowledge': "Открыть knowledge",
  'employeeWorkspace.openNotifications': "Все уведомления",
  'employeeWorkspace.openProfile': "Открыть профиль",
  'employeeWorkspace.openReports': "Открыть отчёты",
  'employeeWorkspace.openRuntime': "Открыть Runtime",
  'employeeWorkspace.overviewSummary': "Этот desktop агрегирует задачи, runtime, handoffs, knowledge, отчёты, чаты и решения в scope этого сотрудника.",
  'employeeWorkspace.pageDescription': "Личный desktop цифрового сотрудника — текущая работа, повестка, knowledge, handoffs, runtime и активность в одном месте.",
  'employeeWorkspace.pageTitle': "{name} — рабочее место",
  'employeeWorkspace.principleNote': "Правило workspace: одна страница — кто я, над чем работаю, что ждёт моего решения и куда перейти дальше — без execution Runtime из этого view.",
  'employeeWorkspace.sections.activity': "Моя активность",
  'employeeWorkspace.sections.approvals': "Ожидает решения",
  'employeeWorkspace.sections.chats': "Недавние чаты",
  'employeeWorkspace.sections.currentRun': "Runtime",
  'employeeWorkspace.sections.currentTasks': "Текущие задачи",
  'employeeWorkspace.sections.knowledge': "Назначенная knowledge",
  'employeeWorkspace.sections.notifications': "Уведомления",
  'employeeWorkspace.sections.overview': "Кто я",
  'employeeWorkspace.sections.pendingHandoffs': "Ожидающие handoffs",
  'employeeWorkspace.sections.recentExecutions': "Недавние executions",
  'employeeWorkspace.sections.reports': "Недавние отчёты",
  'employeeWorkspace.sections.today': "Сегодня",
  'employeeWorkspace.unreadCount': "{count} непрочитанных уведомлений",
  'eventEngine.localOnly': "Хранится в localStorage (ai-company-events) — seed data в V1; модули emit через emitEvent().",
  'eventEngine.scopes.employee': "Сотрудник · {name}",
  'eventEngine.scopes.workspace': "Workspace · {name}",
  'eventEngine.stats.withWorkspace': "Связано с workspace",
  'eventEngine.types.collaboration.completed': "Коллаборация завершена",
  'eventEngine.types.collaboration.consensus': "Консенсус коллаборации",
  'eventEngine.types.collaboration.message': "Сообщение коллаборации",
  'eventEngine.types.collaboration.started': "Коллаборация начата",
  'eventEngine.types.handoff.accepted': "Handoff принят",
  'eventEngine.types.handoff.created': "Handoff создан",
  'eventEngine.types.handoff.rejected': "Handoff отклонён",
  'eventEngine.types.handoff.returned': "Handoff возвращён",
  'eventEngine.types.handoff.sent': "Handoff отправлен",
  'eventEngine.types.runtime.failed': "Runtime завершился с ошибкой",
  'eventEngine.types.runtime.started': "Runtime запущен",
  'eventEngine.types.sprint.completed': "Спринт завершён",
  'eventEngine.types.sprint.planned': "Спринт запланирован",
  'eventEngine.types.sprint.started': "Спринт начат",
  'executionEngine.inspectorTitle': "Инспектор execution",
  'executionEngine.openPhotoLab': "AI Photo Lab",
  'executionEngine.scope.company': "Очередь компании",
  'executionEngine.scope.employee': "Очередь сотрудника",
  'executionEngine.scope.project': "Очередь проекта",
  'executionEngine.scope.workspace': "Очередь workspace",
  'executionEngine.taskId': "ID задачи",
  'executiveDashboard.actionFlow': "Flow workspace",
  'executiveDashboard.actionOpenControlRoom': "Control Room AI Photo Lab",
  'executiveDashboard.actionOpenSprint': "Спринт 1 — рабочий MVP",
  'handoffEngine.actions.accept': "Принять результат",
  'handoffEngine.actions.cancel': "Отменить handoff",
  'handoffEngine.actions.markInProgress': "Отметить в работе",
  'handoffEngine.actions.mockReturn': "Mock внешнего возврата",
  'handoffEngine.actions.prepare': "Собрать пакет",
  'handoffEngine.actions.reject': "Отклонить результат",
  'handoffEngine.actions.requestApproval': "Запросить согласование Owner",
  'handoffEngine.actions.send': "Отправить handoff (mock)",
  'handoffEngine.backToHandoffs': "Назад к handoffs",
  'handoffEngine.catalogTitle': "Каталог handoff",
  'handoffEngine.createSample': "Создать sample handoff",
  'handoffEngine.empty': "Handoff пока нет — активируйте AI Photo Lab или создайте sample handoff.",
  'handoffEngine.fields.blockers': "Блокеры",
  'handoffEngine.fields.deliveredAt': "Доставлено",
  'handoffEngine.fields.expectedResult': "Ожидаемый результат",
  'handoffEngine.fields.paths': "Связанные пути",
  'handoffEngine.fields.preparedBy': "Подготовил",
  'handoffEngine.fields.project': "Проект",
  'handoffEngine.fields.responseFormat': "Формат ответа",
  'handoffEngine.filtersTitle': "Фильтры",
  'handoffEngine.localOnly': "Хранится в localStorage (ai-company-handoffs) — только mock-протокол, без Codex/Cursor API.",
  'handoffEngine.mockReturn.changedFiles': "Изменённые файлы",
  'handoffEngine.mockReturn.notes': "Только mock return — без Codex/Cursor API в V1.",
  'handoffEngine.mockReturn.responseFormat': "Markdown summary",
  'handoffEngine.mockReturn.summary': "Mock внешний результат возвращён в AI Company.",
  'handoffEngine.noChecklist': "Нет пунктов checklist.",
  'handoffEngine.notFoundDescription': "Этот handoff отсутствует в local storage.",
  'handoffEngine.notFoundTitle': "Handoff не найден",
  'handoffEngine.openAll': "Все handoffs",
  'handoffEngine.openDetails': "Открыть детали",
  'handoffEngine.openPhotoLab': "AI Photo Lab",
  'handoffEngine.openProject': "Открыть проект",
  'handoffEngine.package.acceptanceCriteria': "Критерии приёмки",
  'handoffEngine.package.commands': "Команды",
  'handoffEngine.package.constraints': "Ограничения",
  'handoffEngine.package.currentState': "Текущее состояние",
  'handoffEngine.package.expectedResponseFormat': "Ожидаемый формат ответа",
  'handoffEngine.package.files': "Файлы / пути",
  'handoffEngine.package.projectContext': "Контекст проекта",
  'handoffEngine.package.taskContext': "Контекст задачи",
  'handoffEngine.packageNotReady': "Пакет ещё не собран — сначала подготовьте handoff.",
  'handoffEngine.pageDescription': "Протокол передачи реальной работы — цифровые сотрудники готовят пакеты для Codex, Claude Code, Cursor или людей. Без внешнего execution в V1.",
  'handoffEngine.previewTitle': "Превью пакета",
  'handoffEngine.principleNote': "Правило handoff: цифровые сотрудники готовят работу, Owner одобряет, внешний executor выполняет, результат возвращается в AI Company с отчётом и обновлениями timeline.",
  'handoffEngine.priorities.critical': "Критичный",
  'handoffEngine.priorities.high': "Высокий",
  'handoffEngine.priorities.low': "Низкий",
  'handoffEngine.priorities.medium': "Средний",
  'handoffEngine.projectEmpty': "Handoff для этого проекта пока нет.",
  'handoffEngine.projectPanelDescription': "Подготовленные пакеты для Codex, Cursor, QA, DevOps и human executors. Owner одобряет перед отправкой; результаты возвращаются в AI Company.",
  'handoffEngine.projectPanelTitle': "Внешние handoff работы",
  'handoffEngine.rejectReasons.needsRevision': "Нужна доработка перед принятием.",
  'handoffEngine.relatedHandoffs': "Связанные handoffs",
  'handoffEngine.sections.checklist': "Checklist",
  'handoffEngine.sections.instructions': "Инструкции",
  'handoffEngine.sections.package': "Пакет handoff",
  'handoffEngine.sections.result': "Возвращённый результат",
  'handoffEngine.selectHandoff': "Выберите handoff для превью пакета.",
  'handoffEngine.stats.accepted': "Принято",
  'handoffEngine.stats.inProgress': "Отправлено / в работе",
  'handoffEngine.stats.ready': "Готово",
  'handoffEngine.stats.total': "Всего handoffs",
  'handoffEngine.statuses.accepted': "Принято",
  'handoffEngine.statuses.in_progress': "В работе",
  'handoffEngine.statuses.ready': "Готово",
  'handoffEngine.statuses.returned': "Возвращено",
  'handoffEngine.statuses.sent': "Отправлено",
  'handoffEngine.targets.claude_code': "Claude Code",
  'handoffEngine.targets.codex': "Codex",
  'handoffEngine.targets.cursor': "Cursor",
  'handoffEngine.targets.designer': "Дизайнер",
  'handoffEngine.targets.devops': "DevOps",
  'handoffEngine.targets.human_developer': "Human Developer",
  'handoffEngine.targets.qa': "QA",
  'handoffEngine.templatesTitle': "Шаблоны handoff",
  'labels.id': "ID",
  'labels.sla': "SLA",
  'nav.companies': "Компании",
  'nav.flow': "Flow",
  'nav.missionControl': "Mission Control",
  'nav.notifications': "Уведомления",
  'nav.runtime': "Runtime",
  'notificationEngine.approvalInbox': "Уведомления согласований",
  'notificationEngine.bellLabel': "Уведомления",
  'notificationEngine.categories.chat': "Чат",
  'notificationEngine.categories.project': "Проект",
  'notificationEngine.categories.runtime': "Runtime",
  'notificationEngine.chatInbox': "Уведомления чатов",
  'notificationEngine.filters.unread': "Непрочитанные",
  'notificationEngine.localOnly': "Хранится в localStorage (ai-company-notifications) — синхронизировано из events и audit в V1.",
  'notificationEngine.markAllRead': "Отметить все прочитанными",
  'notificationEngine.markRead': "Отметить прочитанным",
  'notificationEngine.pageDescription': "Единый операционный inbox — каждое важное событие платформы создаёт уведомление для Owner с severity, контекстом и deep links.",
  'notificationEngine.principleNote': "Принцип уведомлений: emitEvent() и audit actions автоматически добавляют элементы в inbox — Owner проверяет одну поверхность вместо каждой страницы модуля.",
  'notificationEngine.reportInbox': "Уведомления отчётов",
  'notificationEngine.runtimeInbox': "Уведомления Runtime",
  'notificationEngine.searchPlaceholder': "Название, summary, category, сотрудник…",
  'notificationEngine.stats.approval': "Непрочитанные согласования",
  'notificationEngine.stats.runtime': "Непрочитанные Runtime",
  'notificationEngine.stats.unread': "Непрочитанные",
  'notificationEngine.timelineHint': "События Timeline также появляются в Notification Center с actionable links.",
  'notificationEngine.unreadCount': "{count} непрочитанных уведомлений",
  'notificationEngine.viewInbox': "Открыть inbox",
  'pages.collaboration': "Коллаборация",
  'pages.companies': "Компании",
  'pages.controlRoom': "Control Room AI Photo Lab",
  'pages.flow': "Flow Workspace",
  'pages.handoffs': "Передачи работы",
  'pages.missionControl': "Mission Control",
  'pages.runtimeLive': "Live-монитор Runtime",
  'pages.sprint': "Спринт",
  'pages.visualLab': "Visual Execution Lab",
  'photoLabControlRoom.codexCategories.bug_fix': "Исправления багов",
  'photoLabControlRoom.codexCategories.complex_code': "Сложные изменения кода",
  'photoLabControlRoom.codexCategories.ollama_integration': "Интеграция Ollama",
  'photoLabControlRoom.codexCategories.pdf_report': "PDF / report engine",
  'photoLabControlRoom.codexCategories.production_deploy': "Production deployment",
  'photoLabControlRoom.codexCategories.ui_implementation': "Реализация UI",
  'photoLabControlRoom.codexNote': "Задачи направляются в Codex по директиве Owner — цифровые сотрудники аудируют и планируют; Codex реализует в ~/projects/ai-photo-lab.",
  'photoLabControlRoom.deadline': "Дедлайн",
  'photoLabControlRoom.decisionKinds.approval': "Согласование",
  'photoLabControlRoom.decisionKinds.decision': "Решение",
  'photoLabControlRoom.decisionKinds.review': "Review",
  'photoLabControlRoom.demoItems.ai_analysis': "AI-анализ",
  'photoLabControlRoom.demoItems.deployment_checklist': "Deployment checklist",
  'photoLabControlRoom.demoItems.inspection_chat': "Inspection chat",
  'photoLabControlRoom.demoItems.local_run': "Локальный запуск",
  'photoLabControlRoom.demoItems.manual_zone_edit': "Ручное редактирование зон",
  'photoLabControlRoom.demoItems.mobile_view': "Мобильный вид",
  'photoLabControlRoom.demoItems.photo_upload': "Загрузка фото",
  'photoLabControlRoom.demoItems.production_health': "Здоровье production",
  'photoLabControlRoom.demoItems.report_history': "Отчёт / история",
  'photoLabControlRoom.demoItems.visual_zones': "Visual zones",
  'photoLabControlRoom.demoReady': "demo checks готовы",
  'photoLabControlRoom.empty.blocked': "Блокеров нет.",
  'photoLabControlRoom.empty.decisions': "Решений Owner не ожидается.",
  'photoLabControlRoom.empty.doneToday': "Завершений сегодня пока нет.",
  'photoLabControlRoom.empty.reports': "Черновиков отчётов пока нет.",
  'photoLabControlRoom.empty.risks': "Риски не зафиксированы.",
  'photoLabControlRoom.empty.runtime': "Runtime runs для этого проекта нет.",
  'photoLabControlRoom.empty.waiting': "Ничего не ожидает согласования.",
  'photoLabControlRoom.empty.working': "Нет задач в активном execution.",
  'photoLabControlRoom.health': "Здоровье",
  'photoLabControlRoom.healthLevels.at_risk': "Под риском",
  'photoLabControlRoom.healthLevels.on_track': "По плану",
  'photoLabControlRoom.localNote': "Mock delivery data — только localStorage, без production или вызовов Ollama.",
  'photoLabControlRoom.mvpReady': "Готовность MVP",
  'photoLabControlRoom.noCurrentTask': "Нет активной задачи",
  'photoLabControlRoom.notFoundDescription': "Активируйте AI Photo Lab в projects для seed delivery data.",
  'photoLabControlRoom.notFoundTitle': "Control Room недоступен",
  'photoLabControlRoom.openCanvas': "Открыть Canvas",
  'photoLabControlRoom.openControlRoom': "Открыть Control Room",
  'photoLabControlRoom.openExecution': "Очередь execution",
  'photoLabControlRoom.openKickoff': "Kickoff понедельника",
  'photoLabControlRoom.openProject': "Открыть проект",
  'photoLabControlRoom.openRuntime': "Runtime",
  'photoLabControlRoom.ownerDecisions': "Требуются решения Owner",
  'photoLabControlRoom.pageDescription': "Control Room delivery — MVP readiness, нагрузка команды, handoff Codex и решения Owner с одного экрана.",
  'photoLabControlRoom.pendingApprovals': "Ожидающие согласования",
  'photoLabControlRoom.progress': "Прогресс",
  'photoLabControlRoom.riskLevel': "Уровень риска",
  'photoLabControlRoom.riskStatuses.accepted': "Принят",
  'photoLabControlRoom.riskStatuses.closed': "Закрыт",
  'photoLabControlRoom.riskStatuses.mitigated': "Смягчён",
  'photoLabControlRoom.riskStatuses.open': "Открыт",
  'photoLabControlRoom.sections.codexHandoff': "Codex Handoff",
  'photoLabControlRoom.sections.decisions': "Решения",
  'photoLabControlRoom.sections.deliveryProgress': "Прогресс delivery",
  'photoLabControlRoom.sections.deliveryTasks': "Delivery-задачи (13)",
  'photoLabControlRoom.sections.demoReadiness': "Готовность к demo",
  'photoLabControlRoom.sections.digitalTeam': "Цифровая команда",
  'photoLabControlRoom.sections.mvpStatus': "Статус MVP",
  'photoLabControlRoom.sections.quickLinks': "Быстрые ссылки",
  'photoLabControlRoom.sections.risks': "Риски и блокеры",
  'photoLabControlRoom.sections.runtimeActivity': "Активность Runtime",
  'photoLabControlRoom.sections.workNow': "Работа сейчас",
  'photoLabControlRoom.stats.codex': "Handoffs Codex",
  'photoLabControlRoom.stats.decisions': "Решения Owner",
  'photoLabControlRoom.stats.demoReady': "Demo checks",
  'photoLabControlRoom.stats.tasks': "Delivery-задачи",
  'photoLabControlRoom.title': "Control Room AI Photo Lab",
  'photoLabControlRoom.workNow.blocked': "Заблокировано",
  'photoLabControlRoom.workNow.currentlyWorking': "Сейчас работают",
  'photoLabControlRoom.workNow.doneToday': "Завершено сегодня",
  'photoLabKickoff.actions.openCodexHandoff': "Handoff Codex",
  'photoLabKickoff.actions.openDemoChecklist': "Demo checklist",
  'photoLabKickoff.actions.openLiveRuntime': "Live Runtime",
  'photoLabKickoff.actions.openRunTask': "Run Task",
  'photoLabKickoff.actions.openSprint': "Открыть спринт",
  'photoLabKickoff.actions.openVisualLab': "Visual Lab",
  'photoLabKickoff.actions.startAtlas': "Запустить Atlas (планирование)",
  'photoLabKickoff.actions.startMax': "Запустить MAX (технический аудит)",
  'photoLabKickoff.actions.startQa': "Запустить QA (demo review)",
  'photoLabKickoff.checklistStatus.blocked': "Заблокировано",
  'photoLabKickoff.checklistStatus.done': "Готово",
  'photoLabKickoff.checklistStatus.in_progress': "В работе",
  'photoLabKickoff.checklistStatus.pending': "Ожидает",
  'photoLabKickoff.cto.codexScope': "Объём Codex",
  'photoLabKickoff.cto.priorities': "Приоритеты",
  'photoLabKickoff.cto.weekGoal': "Цель недели",
  'photoLabKickoff.demoOverall.blocked': "Заблокировано",
  'photoLabKickoff.demoOverall.needs_fix': "Нужна доработка",
  'photoLabKickoff.demoOverall.ready': "Готово",
  'photoLabKickoff.demoReadyLabel': "gates готовы",
  'photoLabKickoff.gateStatus.blocked': "Заблокировано",
  'photoLabKickoff.gateStatus.needs_fix': "Нужна доработка",
  'photoLabKickoff.gateStatus.ready': "Готово",
  'photoLabKickoff.links.controlRoom': "Control Room",
  'photoLabKickoff.owner.approvals': "Ожидающие согласования",
  'photoLabKickoff.owner.decisions': "Решения Owner",
  'photoLabKickoff.sections.actions': "Действия kickoff",
  'photoLabKickoff.sections.ctoPlan': "План CTO",
  'photoLabKickoff.sections.demoReadiness': "Готовность к demo",
  'photoLabKickoff.sections.maxHandoff': "Handoff MAX → Codex",
  'photoLabKickoff.sections.ownerApprovals': "Согласования Owner",
  'photoLabKickoff.sections.qaChecklist': "QA checklist",
  'photoLabKickoff.sections.sprintGoal': "Цель спринта",
  'photoLabKickoff.sprint.health': "Здоровье",
  'photoLabKickoff.sprint.name': "Спринт",
  'photoLabKickoff.stats.decisions': "Решения",
  'photoLabKickoff.stats.demoReady': "Demo gates",
  'photoLabKickoff.stats.progress': "Прогресс",
  'photoLabKickoff.title': "Kickoff AI Photo Lab",
  'presence.currentWork.expectedFinish': "Ожидаемое завершение",
  'presence.currentWork.project': "Проект",
  'presence.currentWork.run': "Запуск Runtime",
  'presence.currentWork.title': "Текущая работа",
  'presence.dashboard.available': "Доступен",
  'presence.dashboard.currentAssignment': "Текущее назначение",
  'presence.dashboard.needsAttention': "Требует внимания",
  'presence.dashboard.nowWorking': "Сейчас работает",
  'presence.dashboard.recentlyFinished': "Недавно завершили",
  'presence.dashboard.recentReports': "Недавние отчёты",
  'presence.dashboard.todaysActivity': "Активность за сегодня",
  'presence.dashboard.waiting': "Ожидает",
  'presence.expected': "ETA",
  'presence.status.available': "Доступен",
  'presence.status.break': "Перерыв",
  'presence.status.busy': "Занят",
  'presence.status.in_discussion': "В обсуждении",
  'presence.status.learning': "Обучение",
  'presence.status.offline': "Не в сети",
  'presence.status.waiting_approval': "Ожидает согласования",
  'presence.timeline.title': "Timeline рабочего дня",
  'presence.workdayTypes.break': "Перерыв",
  'presence.workdayTypes.learning': "Обучение",
  'projects.activity.title': "Активность проекта",
  'projects.board.columns.backlog': "Backlog",
  'projects.board.columns.in_progress': "В работе",
  'projects.board.columns.review': "Заблокировано",
  'projects.board.title': "Доска проекта",
  'projects.chats.title': "Чаты проекта",
  'projects.dashboard.approvalsSub': "ожидающих решений",
  'projects.dashboard.assignmentsSub': "активных назначений в workspace",
  'projects.dashboard.health': "Здоровье проекта",
  'projects.dashboard.recentDiscussions': "Недавние обсуждения",
  'projects.dashboard.risks': "Открытые риски",
  'projects.dashboard.runtimeQueue': "Очередь Runtime",
  'projects.dashboard.sprintProgress': "Прогресс спринта",
  'projects.dashboard.teamActivity': "Активность команды",
  'projects.future.budget': "Бюджет",
  'projects.future.client': "Клиент",
  'projects.future.invoices': "Счета",
  'projects.future.releases': "Релизы",
  'projects.knowledge.title': "База знаний проекта",
  'projects.milestones.short': "вех",
  'projects.milestones.status.blocked': "Заблокировано",
  'projects.milestones.title': "Вехи",
  'projects.milestoneStatus.at_risk': "Под риском",
  'projects.milestoneStatus.blocked': "Заблокировано",
  'projects.milestoneStatus.done': "Готово",
  'projects.milestoneStatus.in_progress': "В работе",
  'projects.milestoneStatus.pending': "Ожидает",
  'projects.reports.title': "Отчёты проекта",
  'projects.roadmap.horizons.later': "Позже",
  'projects.roadmap.horizons.next': "Далее",
  'projects.roadmap.horizons.now': "Сейчас",
  'projects.roadmap.title': "Roadmap",
  'projects.runtime.settings': "Настройки Runtime",
  'projects.runtime.title': "Очередь Runtime",
  'projects.runtime.viewRuns': "История запусков",
  'projects.tabs.handoffs': "Handoffs",
  'projects.tabs.milestones': "Вехи",
  'projects.tabs.roadmap': "Roadmap",
  'projects.tabs.runtime': "Runtime",
  'projects.tasks.expectedOutput': "Ожидаемый результат",
  'projects.tasks.title': "Delivery-задачи",
  'projects.taskStatus.backlog': "Backlog",
  'projects.taskStatus.blocked': "Заблокировано",
  'projects.team.roles.architect': "Архитектор",
  'projects.team.roles.designer': "Дизайнер",
  'projects.team.roles.developer': "Разработчик",
  'projects.team.roles.lead': "Лид",
  'projects.team.roles.pm': "PM",
  'projects.team.roles.qa': "QA",
  'projects.team.title': "Команда проекта",
  'projects.timeline.title': "Timeline проекта",
  'projects.timeline.viewCompany': "Timeline компании",
  'reports.types.devops': "DevOps",
  'reports.types.qa': "QA",
  'runtimeEngine.connectionStatuses.mock': "Mock (V1)",
  'runtimeEngine.employeePageTitle': "{name} — профиль Runtime",
  'runtimeEngine.employeeRuntimePage': "Runtime сотрудника",
  'runtimeEngine.employeeSectionTitle': "Профиль Runtime",
  'runtimeEngine.localOnly': "Хранится в localStorage (ai-company-runtime-profiles) — без вызовов Ollama или облака в V1.",
  'runtimeEngine.models.mockLocal': "Mock Local Model",
  'runtimeEngine.openRuntime': "Runtime",
  'runtimeEngine.stats.totalProfiles': "Профили Runtime",
  'runtimeLive.bottomPanel': "Логи / события / предупреждения",
  'runtimeLive.contextAndPreview': "Контекст Runtime + превью результата",
  'runtimeLive.currentStep': "Текущий шаг",
  'runtimeLive.description': "Наблюдайте за execution цифрового сотрудника в реальном времени — pipeline, логи, здоровье провайдера, превью результата и downstream-интеграции.",
  'runtimeLive.elapsed': "Прошло",
  'runtimeLive.employeeWorkspace': "Workspace сотрудника",
  'runtimeLive.eventsEmpty': "Событий timeline для этого run пока нет.",
  'runtimeLive.executionStream': "Live-поток execution",
  'runtimeLive.executionStreamDescription': "Объединённый pipeline, логи провайдера и события timeline для активного запуска.",
  'runtimeLive.launchTitle': "Запустить execution",
  'runtimeLive.liveBadge': "LIVE",
  'runtimeLive.localOnly': "Опрашивает localStorage каждые 500 мс, пока run активен.",
  'runtimeLive.noRunSelected': "Runtime run не выбран — запустите execution Atlas или MAX выше.",
  'runtimeLive.principleNote': "Live-монитор читает локальные runtime runs, логи провайдера и события компании — без внешней телеметрии в V1.",
  'runtimeLive.reportCreation': "Создание отчёта",
  'runtimeLive.reportPending': "Отчёт будет создан после успешного execution.",
  'runtimeLive.resultPending': "Ожидание ответа модели…",
  'runtimeLive.resultPreview': "Превью результата",
  'runtimeLive.runHistory': "История запусков",
  'runtimeLive.selectedEmployee': "Выбранный сотрудник",
  'runtimeLive.streamEmpty': "Запустите runtime run, чтобы заполнить live-поток.",
  'runtimeLive.tabs.events': "События",
  'runtimeLive.tabs.logs': "Логи",
  'runtimeLive.timeout': "Таймаут",
  'runtimeLive.title': "Live-монитор Runtime",
  'runtimeOrchestrator.completionTokens': "Completion tokens",
  'runtimeOrchestrator.contextLayers.runtime_profile': "Профиль Runtime",
  'runtimeOrchestrator.contextTitle': "Контекст Runtime",
  'runtimeOrchestrator.pipelineSteps.run_model_router': "Запуск Model Router",
  'runtimeOrchestrator.pipelineStepStatuses.active': "Активно",
  'runtimeOrchestrator.pipelineStepStatuses.done': "Готово",
  'runtimeOrchestrator.pipelineStepStatuses.failed': "Ошибка",
  'runtimeOrchestrator.pipelineStepStatuses.pending': "Ожидает",
  'runtimeOrchestrator.pipelineStepStatuses.skipped': "Пропущено",
  'runtimeOrchestrator.promptTokens': "Prompt tokens",
  'runtimeOrchestrator.runPageTitle': "Запуск Runtime",
  'runtimeOrchestrator.waitingApprovalNote': "Run приостановлен на approval gate — для завершения нужно mock-согласование Owner.",
  'sprintEngine.burndownNote': "Mock burndown — оставшиеся story points vs идеальная линия для Спринта 1.",
  'sprintEngine.capacityRemaining': "Оставшаяся ёмкость",
  'sprintEngine.columns.blocked': "Заблокировано",
  'sprintEngine.columns.in_sprint': "В спринте",
  'sprintEngine.columns.ready': "Готово",
  'sprintEngine.commitment': "Commitment",
  'sprintEngine.committed': "взято в работу",
  'sprintEngine.dayProgress': "День {elapsed} из {total} (старт в понедельник)",
  'sprintEngine.definitionOfDone': "Definition of Done",
  'sprintEngine.definitionOfReady': "Definition of Ready",
  'sprintEngine.end': "Завершить",
  'sprintEngine.health.at_risk': "Под риском",
  'sprintEngine.health.blocked': "Заблокировано",
  'sprintEngine.health.on_track': "По плану",
  'sprintEngine.ideal': "Идеально",
  'sprintEngine.localNote': "Только планирование — без execution задач. Данные спринта в localStorage; задачи синхронизированы из delivery backlog.",
  'sprintEngine.metrics.blocked': "Заблокировано",
  'sprintEngine.metrics.health': "Здоровье спринта",
  'sprintEngine.metrics.progress': "Прогресс",
  'sprintEngine.metrics.remaining': "Осталось",
  'sprintEngine.metrics.velocity': "Velocity (mock)",
  'sprintEngine.notFoundDescription': "Активируйте AI Photo Lab и перезагрузите страницу для seed Спринта 1.",
  'sprintEngine.notFoundTitle': "Спринт не найден",
  'sprintEngine.openControlRoom': "Control Room",
  'sprintEngine.openExecution': "Очередь execution",
  'sprintEngine.openProject': "Открыть проект",
  'sprintEngine.openRuntime': "Runtime",
  'sprintEngine.openSprint': "Открыть Спринт 1",
  'sprintEngine.pageDescription': "Спринт 1 для AI Photo Lab — цель, ёмкость, commitment, backlog и board готовы для старта цифровой команды в понедельник.",
  'sprintEngine.plannedSprints': "запланировано",
  'sprintEngine.remaining': "Осталось (burndown)",
  'sprintEngine.reviewNotes': "Заметки спринта",
  'sprintEngine.sections.backlog': "Backlog спринта",
  'sprintEngine.sections.board': "Доска спринта",
  'sprintEngine.sections.burndown': "Burndown",
  'sprintEngine.sections.capacity': "Ёмкость и commitment",
  'sprintEngine.sections.goal': "Цель спринта",
  'sprintEngine.sections.links': "Быстрые ссылки",
  'sprintEngine.sections.progress': "Прогресс спринта",
  'sprintEngine.sections.review': "DoR / DoD / Review",
  'sprintEngine.start': "Запустить",
  'sprintEngine.storyPointsShort': " SP",
  'sprintEngine.tasks': "задач",
  'sprintEngine.title': "Планирование спринта",
  'sprintEngine.workingDays': "рабочих дней",
  'taskResultEngine.actions.archive': "Архивировать",
  'taskResultEngine.actions.createFollowUp': "Создать follow-up задачу",
  'taskResultEngine.actions.requestChanges': "Запросить изменения",
  'taskResultEngine.actions.sendToCodex': "Отправить в handoff Codex",
  'taskResultEngine.actions.sendToQa': "Отправить в QA",
  'taskResultEngine.reviewActions.create_follow_up': "Follow-up задача создана",
  'taskResultEngine.reviewActions.request_changes': "Запрошены изменения",
  'taskResultEngine.reviewActions.send_to_codex': "Отправлено в Codex",
  'taskResultEngine.reviewActions.send_to_qa': "Отправлено в QA",
  'taskResultEngine.reviewActions.submit_for_review': "Отправлено на review",
  'taskResultEngine.sections.review': "Review Owner",
  'taskResultEngine.stats.changesRequested': "Запрошены изменения",
  'taskResultEngine.stats.readyForReview': "Готово к review",
  'taskResultEngine.statuses.changes_requested': "Запрошены изменения",
  'taskResultEngine.statuses.ready_for_review': "Готово к review",
  'taskRunner.actions.start': "Запустить",
  'taskRunner.history.live': "Live",
  'taskRunner.modes.devops_plan': "План DevOps",
  'taskRunner.modes.handoff_preparation': "Подготовка handoff",
  'taskRunner.modes.product_review': "Product review",
  'taskRunner.modes.qa_review': "QA review",
  'taskRunner.modes.technical_audit': "Технический аудит",
  'taskRunner.result.openLive': "Live-монитор",
  'visualLab.actions.build_passed': "Сборка успешна",
  'visualLab.actions.button_added': "Кнопка добавлена",
  'visualLab.actions.click': "Клик по login",
  'visualLab.actions.cursor_move': "Курсор перемещён",
  'visualLab.actions.file_changed': "Файл изменён",
  'visualLab.actions.highlight': "Подсветка UI-элемента",
  'visualLab.actions.screenshot': "Скриншот сохранён",
  'visualLab.actions.terminal_line': "Терминал",
  'visualLab.actions.test_started': "Тест запущен",
  'visualLab.browser.buttonPending': "Отрисовка кнопки Sign in…",
  'visualLab.browser.landingCopy': "Войдите, чтобы продолжить в inspection workspace AI Photo Lab.",
  'visualLab.browser.screenshots': "Timeline скриншотов",
  'visualLab.browser.title': "Превью браузера",
  'visualLab.description': "Visual workspace в стиле Cursor — mock-редактор, терминал, превью браузера, клики и timeline тестов для execution цифрового сотрудника.",
  'visualLab.editor.changed': "Файл изменён",
  'visualLab.editor.title': "Редактор",
  'visualLab.integrations.canvas': "Canvas компании",
  'visualLab.integrations.controlRoom': "Control Room",
  'visualLab.integrations.execution': "Очередь execution",
  'visualLab.integrations.handoffs': "Handoff",
  'visualLab.integrations.runtime': "Запуск Runtime",
  'visualLab.mockNote': "Только visual/mock — без реального Playwright или browser automation.",
  'visualLab.sidebar.execution': "Execution",
  'visualLab.sidebar.project': "Проект",
  'visualLab.sidebar.tests': "Шаги теста",
  'visualLab.terminal.title': "Терминал",
  'visualLab.terminal.waiting': "Ожидание вывода execution…",
  'visualLab.timeline.back': "Назад",
  'visualLab.timeline.forward': "Вперёд",
  'visualLab.timeline.pause': "Пауза",
  'visualLab.timeline.play': "Воспроизвести",
  'visualLab.timeline.replay': "Повтор",
  'visualLab.timeline.restart': "Перезапуск",
  'visualLab.timeline.title': "Timeline действий",
  'visualLab.title': "Visual Execution Lab",
  'workdayEngine.actions.openWorkday': "Рабочий день",
  'workdayEngine.phases.agenda': "Повестка",
  'workdayEngine.phases.day_start': "08:00",
  'workdayEngine.summary.title': "Сводка дня",
  'toolExecutionEngine.pageDescription': "Единый шлюз для запросов инструментов. Только mock-провайдер, без реального выполнения.",
  'toolExecutionEngine.submitSample': "Отправить тестовый запрос",
  'toolExecutionEngine.localNote': "Только локальный mock-поток. Реальные вызовы провайдеров не выполняются.",
  'toolExecutionEngine.stats.total': "Всего",
  'toolExecutionEngine.stats.waitingApproval': "Ожидает согласования",
  'toolExecutionEngine.stats.completed': "Завершено",
  'toolExecutionEngine.stats.failedCancelled': "Ошибка/отменено",
  'toolExecutionEngine.filters.title': "Фильтры",
  'toolExecutionEngine.filters.employee': "Сотрудник",
  'toolExecutionEngine.filters.provider': "Провайдер",
  'toolExecutionEngine.filters.status': "Статус",
  'toolExecutionEngine.filters.approval': "Согласование",
  'toolExecutionEngine.filters.all': "все",
  'toolExecutionEngine.filters.required': "обязательно",
  'toolExecutionEngine.filters.notRequired': "не требуется",
  'toolExecutionEngine.log.title': "Журнал выполнения",
  'toolExecutionEngine.log.items': "{count} записей",
  'toolExecutionEngine.log.empty': "Запусков инструментов пока нет.",
  'toolExecutionEngine.log.selectHint': "Выберите выполнение из журнала.",
  'toolExecutionEngine.details.title': "Детали выполнения",
  'toolExecutionEngine.approval.stateTitle': "Статус согласования",
  'toolExecutionEngine.approval.noAction': "Для текущего статуса действие согласования недоступно.",
  'toolExecutionEngine.approval.requiredTitle': "Требуется согласование",
  'toolExecutionEngine.approval.waitingNote': "Запрос ожидает решения Owner: {toolId} · {action}",
  'toolExecutionEngine.approval.approve': "Одобрить",
  'toolExecutionEngine.approval.reject': "Отклонить",
  'toolExecutionEngine.approval.cancel': "Отменить",
  'toolExecutionEngine.approval.rejectReason': "Отклонено в панели согласования инструмента",
  'toolExecutionEngine.result.executionId': "ID выполнения:",
  'toolExecutionEngine.result.status': "Статус:",
  'toolExecutionEngine.result.elapsed': "время: {ms} мс · завершено: {at}",
  'toolExecutionEngine.result.noResponse': "Ответа пока нет. Ожидание результата выполнения.",
  'toolExecutionEngine.card.mockTag': "mock",
  'toolExecutionEngine.card.selected': "Выбрано",
  'toolExecutionEngine.card.openDetails': "Открыть детали",
  'toolExecutionEngine.statuses.created': "Создано",
  'toolExecutionEngine.statuses.waiting_approval': "Ожидает согласования",
  'toolExecutionEngine.statuses.approved': "Одобрено",
  'toolExecutionEngine.statuses.running': "Выполняется",
  'toolExecutionEngine.statuses.completed': "Завершено",
  'toolExecutionEngine.statuses.failed': "Ошибка",
  'toolExecutionEngine.statuses.cancelled': "Отменено",
  'operatingDayEngine.title': "Рабочий день компании",
  'operatingDayEngine.pageDescription': "Полный рабочий день цифровой компании — утренний brief, команда, deliveries, встречи, согласования, runtime, отчёты и вечерняя сводка.",
  'operatingDayEngine.localNote': "Агрегировано из локальных mock-данных — без scheduler и backend.",
  'operatingDayEngine.linksAria': "Быстрые ссылки рабочего дня",
  'operatingDayEngine.flowAria': "Поток рабочего дня",
  'operatingDayEngine.timeOfDay.morning': "Утро",
  'operatingDayEngine.timeOfDay.afternoon': "День",
  'operatingDayEngine.timeOfDay.evening': "Вечер",
  'operatingDayEngine.phases.morning': "Утренний brief",
  'operatingDayEngine.phases.employees': "Сотрудники",
  'operatingDayEngine.phases.currentWork': "Текущая работа",
  'operatingDayEngine.phases.meetings': "Встречи",
  'operatingDayEngine.phases.approvals': "Согласования",
  'operatingDayEngine.phases.runtime': "Runtime",
  'operatingDayEngine.phases.reports': "Отчёты",
  'operatingDayEngine.phases.endOfDay': "Конец дня",
  'operatingDayEngine.sections.morningBrief': "Утренний brief",
  'operatingDayEngine.sections.priorities': "Приоритеты на сегодня",
  'operatingDayEngine.sections.employeesStarted': "Сотрудники начали день",
  'operatingDayEngine.sections.sprintProgress': "Прогресс спринта",
  'operatingDayEngine.sections.risks': "Риски на сегодня",
  'operatingDayEngine.sections.approvals': "Ожидающие согласования",
  'operatingDayEngine.sections.meetings': "Встречи",
  'operatingDayEngine.sections.deliveries': "Deliveries",
  'operatingDayEngine.sections.runtime': "Runtime",
  'operatingDayEngine.sections.reports': "Отчёты",
  'operatingDayEngine.sections.companyHealth': "Здоровье компании",
  'operatingDayEngine.sections.eveningSummary': "Вечерняя сводка",
  'operatingDayEngine.links.commandCenter': "Command Center",
  'operatingDayEngine.links.runtime': "Runtime",
  'operatingDayEngine.links.kickoff': "Kickoff",
  'operatingDayEngine.links.controlRoom': "Control Room",
  'operatingDayEngine.links.taskResults': "Task Results",
  'operatingDayEngine.links.timeline': "Timeline",
  'operatingDayEngine.links.workspace': "Workspace",
  'operatingDayEngine.empty.priorities': "Приоритеты на сегодня не выделены.",
  'operatingDayEngine.empty.employeesStarted': "Сотрудники ещё не начали рабочий день.",
  'operatingDayEngine.empty.risks': "На delivery board нет активных рисков.",
  'operatingDayEngine.empty.deliveries': "Нет активных deliveries в работе.",
  'operatingDayEngine.empty.meetings': "На сегодня нет collaboration-сессий.",
  'operatingDayEngine.evening.finished': "Завершили день",
  'operatingDayEngine.evening.reportsToday': "Отчётов сегодня",
  'operatingDayEngine.evening.tasksActive': "Задач в работе",
  'operatingDayEngine.evening.approvalsPending': "Ожидают согласования",
  'operatingDayEngine.evening.runtimeCompleted': "Runtime завершено",
  'operatingDayEngine.evening.avgPhase': "Средняя фаза workday",
  'operatingDayEngine.evening.note': "Снимок конца дня — синхронизируйте фазы workday или завершите день из workspace сотрудников.",
  'pages.operatingDay': "Рабочий день",
  'sprintEngine.storyPointsShort': " СП",
};
