/**
 * Supplemental Russian translations for missing-ru-values.json (330 entries).
 * Merged into build pipeline after VALUE_RU gaps are identified.
 */
export const SUPPLEMENTAL_VALUE_RU: Record<string, string> = {
  "AI": "ИИ",
  "AI Company · NOC": "AI Company · NOC",
  "AI Summaries": "ИИ-сводки",
  "Action": "Действие",
  "Actor": "Инициатор",
  "Always Allowed": "Всегда разрешено",
  "Always Required": "Всегда обязательно",
  "Analysis": "Анализ",
  "Analyze": "Анализировать",
  "Approval": "Согласование",
  "Approval Granted": "Согласование одобрено",
  "Approval Rejected": "Согласование отклонено",
  "Approval Requested": "Запрошено согласование",
  "Approval for cloud": "Согласование для облака",
  "Approval policies": "Политики согласования",
  "Approve": "Одобрить",
  "Architecture": "Архитектура",
  "Artifact": "Артефакт",
  "Artifacts": "Артефакты",
  "Assign": "Назначить",
  "Assigned Knowledge": "Assigned Knowledge",
  "Assignment": "Назначение",
  "Assignments": "Назначения",
  "Auto Approve": "Автоодобрение",
  "Auto Summaries": "Автосводки",
  "Automation": "Автоматизация",
  "Best Practice": "Лучшая практика",
  "Building": "Формирование",
  "Built at": "Собрано в",
  "Business Analysis": "Бизнес-анализ",
  "Capabilities": "Возможности",
  "Capacity": "Ёмкость",
  "Category": "Категория",
  "Certification": "Сертификация",
  "Chat Message": "Сообщение чата",
  "Chunk embeddings stored platform-side — not in LLM.": "Chunk embeddings stored platform-side — not in LLM.",
  "Closed": "Закрыто",
  "Cloud": "Облако",
  "Cloud OK": "Облако исправно",
  "Cloud allowed": "Облако разрешено",
  "Cloud document storage — REST adapter.": "Cloud document storage — REST adapter.",
  "Code": "Код",
  "Codename": "Кодовое имя",
  "Coding": "Разработка",
  "Coding Agents": "Агенты разработки",
  "Collections": "Коллекции",
  "Comment": "Комментарий",
  "Competencies": "Компетенции",
  "Configure": "Настроить",
  "Connected": "Подключено",
  "Context Loaded": "Контекст загружен",
  "Context layers loaded": "Слои контекста загружены",
  "Context window": "Контекстное окно",
  "Conversation": "Беседа",
  "Conversation Started": "Беседа начата",
  "Core Engineering": "Ядро инженерии",
  "Create": "Создать",
  "Create ADR": "Создать ADR",
  "Create Document": "Создать документ",
  "Create Report": "Создать отчёт",
  "Create Task": "Создать задачу",
  "Created": "Создано",
  "Custom": "Пользовательский",
  "Database Migration": "Миграция БД",
  "Decision": "Решение",
  "Degraded": "Деградация",
  "Delegate": "Делегировать",
  "Delegate to": "Делегировать",
  "Delegated to": "Делегировано",
  "Delete": "Удалить",
  "Deploy": "Развернуть",
  "Development": "Разработка",
  "Direct": "Прямой",
  "Disabled": "Отключено",
  "Disconnected": "Отключено",
  "Discussion": "Обсуждение",
  "Document": "Документ",
  "Documentation": "Документация",
  "Documents": "Документы",
  "Embedding": "Эмбеддинг",
  "Embeddings": "Эмбеддинги",
  "Emit event": "Отправить событие",
  "Employee": "Сотрудник",
  "Employee Created": "Сотрудник создан",
  "Employee Memory": "Employee Memory",
  "Employee Runtime": "Employee Runtime",
  "Employee Updated": "Сотрудник обновлён",
  "Employee id — future manager routing": "ID сотрудника — будущая маршрутизация менеджеру",
  "Employee profile": "Профиль сотрудника",
  "Employee · {name}": "Employee · {name}",
  "Ended": "Завершено",
  "Engineering": "Инженерия",
  "Engineering automation · v1.4": "Инженерная автоматизация · v1.4",
  "Entity links between ADRs, standards, and architecture docs.": "Entity links between ADRs, standards, and architecture docs.",
  "Est. cost": "Прим. стоимость",
  "Est. tokens": "Прим. токены",
  "Estimated cost": "Оценочная стоимость",
  "Estimated tokens": "Оценочное число токенов",
  "Event type": "Тип события",
  "Events Created": "События созданы",
  "Evidence": "Подтверждение",
  "Execute": "Выполнить",
  "Execution Finished": "Выполнение завершено",
  "Execution Started": "Выполнение начато",
  "Executive": "Руководство",
  "Executive Dashboard": "Панель руководства",
  "Experience": "Опыт",
  "Expired": "Истекло",
  "Failed": "Ошибка",
  "Filesystem": "Файловая система",
  "Filesystem Delete": "Удаление из файловой системы",
  "Finance": "Финансы",
  "Findings": "Выводы",
  "Flow workspace": "Flow workspace",
  "From": "От",
  "General": "Общее",
  "Generate": "Сгенерировать",
  "Generated": "Сгенерировано",
  "Generated ADR": "Сгенерированный ADR",
  "Generated Document": "Сгенерированный документ",
  "Generated Report": "Сгенерированный отчёт",
  "Generated Summary": "Сгенерированная сводка",
  "Generated Task": "Сгенерированная задача",
  "Generic Critical Action": "Общее критическое действие",
  "GitHub Push": "GitHub Push",
  "Grant approval (mock)": "Предоставить согласование (mock)",
  "Group": "Группа",
  "Healthy": "Исправен",
  "Hybrid": "Гибридный",
  "ID": "ID",
  "Idle": "Простой",
  "Impact": "Влияние",
  "Imported": "Импортировано",
  "Infrastructure": "Инфраструктура",
  "Instruction": "Инструкция",
  "Invoke": "Вызвать",
  "Issuer": "Инициатор",
  "Knowledge Graph": "Граф знаний",
  "Knowledge Loaded": "Знания загружены",
  "Knowledge Updated": "Знания обновлены",
  "Knowledge records": "Записи знаний",
  "Leadership": "Лидерство",
  "Learning Path": "Learning Path",
  "Link": "Ссылка",
  "Linked run": "Связанный запуск",
  "Load %": "Нагрузка %",
  "Local": "Локальный",
  "Local File": "Локальный файл",
  "Local LLM inference — REST adapter.": "Local LLM inference — REST adapter.",
  "Local first": "Сначала локально",
  "Local only": "Только локально",
  "Login": "Вход",
  "Long-term": "Долгосрочная",
  "Manager": "Менеджер",
  "Manual": "Вручную",
  "Markdown": "Markdown",
  "Marketing": "Маркетинг",
  "Max cost per run": "Макс. стоимость за запуск",
  "Max tokens": "Макс. токены",
  "Max tokens per run": "Макс. токены за запуск",
  "Memory": "Память",
  "Memory Added": "Память добавлена",
  "Memory Architecture": "Memory Architecture",
  "Memory Loaded": "Память загружена",
  "Memory records": "Записи памяти",
  "Memory store": "Хранилище памяти",
  "Mentions: @Atlas, @MAX — future.": "Упоминания: @Atlas, @MAX — в будущем.",
  "Metric": "Метрика",
  "Mock (V1)": "Mock (V1)",
  "Model Selected": "Модель выбрана",
  "Money Transfer": "Денежный перевод",
  "Multi-model cloud routing — REST adapter.": "Multi-model cloud routing — REST adapter.",
  "Native": "Нативный",
  "Natural-language retrieval across knowledge items.": "Natural-language retrieval across knowledge items.",
  "No workspace": "Нет рабочего пространства",
  "Not loaded": "Не загружено",
  "Note": "Заметка",
  "Notify": "Уведомить",
  "Online": "Онлайн",
  "Operations": "Операции",
  "Orchestrator": "Оркестратор",
  "Owner": "Владелец",
  "Owner Only": "Только владелец",
  "Owner → CEO → executives → engineering → QA → operations": "Owner → CEO → executives → engineering → QA → operations",
  "Owner-approved executive summaries of long documents.": "Owner-approved executive summaries of long documents.",
  "Permanent": "Постоянная",
  "Permission": "Разрешение",
  "Permission Change": "Изменение разрешения",
  "Permissions": "Разрешения",
  "Pipeline": "Пайплайн",
  "Placeholder": "Заглушка",
  "Planning": "Планирование",
  "Platform": "Платформа",
  "Platform Shell": "Platform Shell",
  "Platform-wide": "Platform-wide",
  "Product": "Продукт",
  "Product Management": "Управление продуктом",
  "Production Deploy": "Продакшен-развёртывание",
  "Production approvals": "Согласования продакшена",
  "Prompt Pack": "Набор промптов",
  "Provider": "Провайдер",
  "Publish": "Опубликовать",
  "Quote": "Цитата",
  "Read": "Чтение",
  "Recommendations": "Рекомендации",
  "Recommended Reading": "Рекомендуемое к прочтению",
  "Reject": "Отклонить",
  "Relationship": "Связь",
  "Relationships": "Связи",
  "Report": "Отчёт",
  "Report Created": "Отчёт создан",
  "Report Generated": "Отчёт сгенерирован",
  "Require Approval": "Требуется согласование",
  "Requires Approval": "Требует согласования",
  "Research": "Исследование",
  "Review": "Проверка",
  "Reviewing": "На проверке",
  "Reviews": "Проверки",
  "Risks": "Риски",
  "Run": "Запуск",
  "Run Completed": "Запуск завершён",
  "Run Model Router": "Run Model Router",
  "Run id, employee, model, report…": "ID запуска, сотрудник, модель, отчёт…",
  "Runbook": "Runbook",
  "Running": "Выполняется",
  "Runtime": "Runtime",
  "Runtime Profile": "Runtime Profile",
  "Runtime Run": "Runtime Run",
  "Runtime Started": "Runtime Started",
  "Runtime context": "Runtime context",
  "Runtime integration: call queryKnowledgeForRuntime() before task execution — do not store knowledge in model context permanently.": "Runtime integration: call queryKnowledgeForRuntime() before task execution — do not store knowledge in model context permanently.",
  "Runtime profile": "Runtime profile",
  "Runtime profiles": "Runtime profiles",
  "Runtime run": "Runtime run",
  "SMTP/IMAP messaging — REST adapter.": "SMTP/IMAP messaging — REST adapter.",
  "Scope": "Область",
  "Seed models": "Начальные модели",
  "Semantic Search": "Семантический поиск",
  "Sensitive data allowed": "Конфиденциальные данные разрешены",
  "Session": "Сессия",
  "Severity": "Критичность",
  "Short-term": "Краткосрочная",
  "Similarity ranking for task-context injection.": "Similarity ranking for task-context injection.",
  "Skills": "Навыки",
  "Source": "Источник",
  "Squad": "Команда",
  "Squads": "Команды",
  "Standard": "Стандарт",
  "State": "Состояние",
  "Storage": "Хранилище",
  "Stored in localStorage (ai-company-knowledge, ai-company-knowledge-collections) — no vector DB.": "Stored in localStorage (ai-company-knowledge, ai-company-knowledge-collections) — no vector DB.",
  "Streaming": "Потоковая передача",
  "Success": "Успех",
  "Suggested items based on role, assignments, and task history.": "Suggested items based on role, assignments, and task history.",
  "Summary": "Сводка",
  "System": "Система",
  "System Prompt": "System Prompt",
  "System prompt": "System prompt",
  "Tag": "Тег",
  "Target": "Цель",
  "Task": "Задача",
  "Task Completed": "Задача завершена",
  "Task Created": "Задача создана",
  "Temperature": "Температура",
  "Title, employee, action type, status…": "Название, сотрудник, тип действия, статус…",
  "Title, summary, tags, content…": "Название, сводка, теги, содержание…",
  "To": "К",
  "Tool": "Инструмент",
  "Tool Connected": "Инструмент подключён",
  "Tool Connection": "Подключение инструмента",
  "Tool calls": "Вызовы инструментов",
  "Tool gateway": "Шлюз инструментов",
  "Trust score": "Trust score",
  "Type": "Тип",
  "Unassign": "Снять назначение",
  "Update": "Обновить",
  "Vector Search": "Векторный поиск",
  "Verified": "Проверено",
  "View all collections": "Показать все коллекции",
  "Vision": "Видение",
  "WS": "WS",
  "Waiting approval": "Ожидание согласования",
  "Wiki": "Вики",
  "Workflow": "Workflow",
  "Working": "Работает",
  "Workspace": "Рабочее пространство",
  "Workspace Admin": "Администратор рабочего пространства",
  "Workspace Assigned": "Рабочее пространство назначено",
  "Workspace Assignment": "Назначение на рабочее пространство",
  "Workspace Assignments": "Назначения на рабочие пространства",
  "Workspace Created": "Рабочее пространство создано",
  "Workspace Only": "Только рабочее пространство",
  "Workspace Scope": "Область рабочего пространства",
  "Workspace overlay": "Наложение рабочего пространства",
  "Workspace · {name}": "Workspace · {name}",
  "Workspace-linked": "Workspace-linked",
  "Workspace-scoped": "Workspace-scoped",
  "Write": "Запись",
  "backlog": "бэклог",
  "backlog + blocked": "бэклог + заблокировано",
  "blocked": "заблокировано",
  "breach": "нарушение",
  "busy": "занят",
  "capabilities": "возможности",
  "degraded": "деградация",
  "done": "готово",
  "events": "события",
  "findings": "выводы",
  "healthy": "исправен",
  "idle": "простой",
  "live": "активно",
  "local / mock": "локально / mock",
  "local V1": "локальный V1",
  "mock telemetry": "mock-телеметрия",
  "mock · localhost": "mock · localhost",
  "offline": "офлайн",
  "online": "онлайн",
  "org.workflow · main": "org.workflow · main",
  "platform ready": "платформа готова",
  "registry probes ok": "проверки реестра OK",
  "risks": "риски",
  "runs": "запуски",
  "sent": "отправлено",
  "squads": "команды",
  "success": "успех",
  "tools": "инструменты",
  "verified": "проверено",
  "{active} active profiles · {waiting} waiting approval": "{active} активных профилей · {waiting} ожидают согласования",
  "{name} — Memory": "{name} — Memory",
  "{name} — Runtime Profile": "{name} — Runtime Profile",
};
