/** Path-specific Russian overrides for remaining i18n gaps. */
export const PATH_RU_SUPPLEMENT: Record<string, string> = {
  'nav.runtime': 'Runtime',
  'labels.id': 'ID',
  'inspector.lastRun': 'Последний запуск',
  'inspector.noEventsYet': 'Событий пока нет',
  'employees.description':
    'Реестр агентов V1 — активные агенты работают сейчас; запланированные видны для org design.',
  'employees.agents': 'агенты',
  'employees.template': 'Шаблон',
  'organization.customEmployees': 'Кастомные сотрудники',
  'organization.squadRoster': 'Снимок roster команды',
  'organization.agentsUnit': 'агенты',
  'organizationEngine.reportingTreeHint':
    'Owner → CEO → executives → engineering → QA → operations',
  'organizationEngine.departments': 'Отделы',
  'organizationEngine.teams': 'Команды',
  'organizationEngine.teamLead': 'Лид команды',
  'organizationEngine.teamsUnit': 'команд',
  'organizationEngine.membersUnit': 'участников',
  'organizationEngine.reportingLines': 'Линии подчинения',
  'organizationEngine.future.crossFunctionalDesc':
    'Команды через несколько отделов — например, launch task forces.',
  'organizationEngine.future.matrix': 'Матричная организация',
  'organizationEngine.stats.departments': 'Отделы',
  'organizationEngine.stats.teams': 'Команды',
  'organizationEngine.stats.customEmployees': 'Кастомные сотрудники',
  'approvalEngine.requestCount': 'запросов',
  'approvalEngine.futureIntegrationHint':
    'Runtime создаёт Approval Request → Owner проверяет → решение emit Audit Event.',
  'approvalEngine.futureIntegrations.0': 'GitHub Push',
  'approvalEngine.runtimeNote':
    'Runtime integration: invoke createApprovalRequest() instead of executing protected actions. Owner decision writes to audit trail.',
  'approvalEngine.localOnly':
    'Хранится в localStorage (ai-company-approvals) — Runtime не подключён.',
  'approvalEngine.ownerActionsTitle': 'Проверка Owner',
  'approvalEngine.emptyListDescription':
    'Когда Runtime запрашивает human approval, запросы появляются здесь для проверки Owner.',
  'approvalEngine.actionTypes.github_push': 'GitHub Push',
  'knowledgeEngine.platformWide': 'Platform-wide',
  'knowledgeEngine.assignedKnowledgeTitle': 'Assigned Knowledge',
  'knowledgeEngine.runtimeNote':
    'Runtime integration: call queryKnowledgeForRuntime() before task execution — do not store knowledge in model context permanently.',
  'knowledgeEngine.localOnly':
    'Stored in localStorage (ai-company-knowledge, ai-company-knowledge-collections) — no vector DB.',
  'knowledgeEngine.stats.platformWide': 'Platform-wide',
  'knowledgeEngine.stats.workspaceScoped': 'Workspace-scoped',
  'knowledgeEngine.types.runbook': 'Runbook',
  'knowledgeEngine.sources.markdown': 'Markdown',
  'knowledgeEngine.future.semanticSearchDesc':
    'Natural-language retrieval across knowledge items.',
  'knowledgeEngine.future.vectorSearchDesc':
    'Similarity ranking for task-context injection.',
  'knowledgeEngine.future.embeddingsDesc':
    'Chunk embeddings stored platform-side — not in LLM.',
  'knowledgeEngine.future.knowledgeGraphDesc':
    'Entity links between ADRs, standards, and architecture docs.',
  'knowledgeEngine.future.aiSummariesDesc':
    'Owner-approved executive summaries of long documents.',
  'knowledgeEngine.future.recommendedReadingDesc':
    'Suggested items based on role, assignments, and task history.',
  'dashboard.runningTasks': 'Running tasks',
  'dashboard.queueDepth': 'Queue depth',
  'dashboard.toolsHealthy': 'Tools healthy',
  'executiveDashboard.employeesSub': 'зарегистрированных цифровых сотрудников',
  'executiveDashboard.approvalsSub': 'ожидающих решений',
  'executiveDashboard.reportsSub': 'сгенерированных artifacts',
  'executiveDashboard.workspacesSub': 'workspaces в реестре',
  'executiveDashboard.actionFlow': 'Flow workspace',
  'tasks.queue': 'Очередь задач',
  'employeeBuilder.sections.identity': 'Identity',
  'employeeBuilder.sections.templates': 'Шаблон',
  'employeeBuilder.sections.restrictions': 'Ограничения',
  'employeeBuilder.sections.systemPrompt': 'System Prompt',
  'employeeBuilder.sections.workflow': 'Workflow',
  'employeeBuilder.sections.memoryScope': 'Memory Scope',
  'employeeBuilder.sections.mission': 'Миссия',
  'employeeBuilder.fields.systemPrompt': 'System prompt',
  'employeeBuilder.fields.workflow': 'Workflow',
  'employeeBuilder.fields.memoryScope': 'Memory scope',
  'employeeBuilder.placeholders.systemPrompt':
    'Вы — цифровой специалист. Определите тон, границы и правила решений…',
  'employeeBuilder.placeholders.workflow':
    'Пошаговый flow: intake → analysis → output → review',
  'employeeBuilder.options.restrictions.No Production Deploy': 'No Production Deploy',
  'employeeBuilder.options.restrictions.No Backend Changes': 'No Backend Changes',
  'employeeBuilder.options.restrictions.No Database Write': 'No Database Write',
  'employeeBuilder.options.restrictions.No Git Push': 'No Git Push',
  'employeeBuilder.options.restrictions.No Delete Operations': 'No Delete Operations',
  'toolRegistry.detailsTitle': 'Детали инструмента',
  'toolRegistry.architectureNote':
    'Только архитектура V1 — без реальных подключений. Employees invoke tools через Registry; MCP/GitHub/Docker adapters — future.',
  'toolRegistry.catalogTitle': 'Каталог инструментов',
  'toolRegistry.details.identity': 'Identity инструмента',
  'toolRegistry.providerDescriptions.native':
    'In-process platform adapters (browser, desktop).',
  'toolRegistry.policyHints.require-approval': 'Owner must approve before invoke.',
  'toolRegistry.policyHints.disabled': 'Tool blocked — no invoke permitted.',
  'toolRegistry.descriptions.email': 'SMTP/IMAP messaging — REST adapter.',
  'toolRegistry.descriptions.googleDrive': 'Cloud document storage — REST adapter.',
  'toolRegistry.descriptions.ollama': 'Local LLM inference — REST adapter.',
  'toolRegistry.descriptions.openrouter': 'Multi-model cloud routing — REST adapter.',
  'toolRegistry.descriptions.ssh': 'Remote shell access — CLI adapter (high risk).',
  'flow.breadcrumb': 'org.workflow · main',
  'flow.nodes': 'узлов',
  'flow.executeWorkflow': 'Execute Workflow',
  'shell.platformShell': 'Platform Shell',
  'brand.env': 'mock · localhost',
  'discussions.discussionCount': 'обсуждений',
  'discussions.participantsCount': 'участников',
  'discussions.localOnly': 'Хранится локально — runtime не подключён',
  'discussions.composerPlaceholder': 'Напишите сообщение как Owner…',
  'discussions.mockReplies.3':
    '{name}: QA потребует явные acceptance criteria перед продолжением.',
  'sideNav.subtitle': 'AI Company · NOC',
  'conversations.localOnly': 'Хранится локально — runtime не подключён',
  'conversations.composerPlaceholder': 'Напишите сообщение как Owner…',
  'conversations.mockReplies.2':
    '{name}: Полезное направление. Помогу структурировать следующий шаг, когда будете готовы.',
  'conversations.mockReplies.4':
    '{name}: Принято. Спрашивайте в любое время — conversation сохраняется между сессиями.',
  'chats.participants': 'участников',
  'chats.localOnly': 'Хранится локально — runtime не подключён',
  'chats.composerPlaceholder': 'Напишите сообщение как Owner…',
  'chats.systemStartedWorkspace': 'Workspace chat привязан к {name}.',
  'chats.mockReplies.3':
    '{name}: QA потребует явные acceptance criteria перед продолжением.',
  'workspaces.localOnly': 'Хранится локально — runtime не подключён',
  'workspaces.assignmentCount': 'назначений',
  'workspaces.navLabel': 'Секции workspace',
  'workspaces.newFormTitle': 'Настройка workspace',
  'workspaces.settings.title': 'Настройки workspace',
  'workspaces.errors.nameRequired': 'Название workspace обязательно.',
  'reports.localOnly':
    'Хранится в localStorage — mock/seed data в V1, без Runtime.',
  'audit.localOnly':
    'Хранится в localStorage — seed events в V1, Runtime будет дописывать live.',
  'eventEngine.localOnly':
    'Stored in localStorage (ai-company-events) — seed data in V1; modules emit via emitEvent().',
  'eventEngine.scopes.employee': 'Employee · {name}',
  'eventEngine.scopes.workspace': 'Workspace · {name}',
  'eventEngine.stats.withWorkspace': 'Workspace-linked',
  'eventEngine.types.runtime.started': 'Runtime Started',
  'runEngine.runtimeRunId': 'Runtime run',
  'runEngine.platformWide': 'Platform-wide',
  'runEngine.localOnly':
    'Stored in localStorage (ai-company-run-history) — Runtime will append records when connected.',
  'runtimeEngine.employeePageTitle': '{name} — Runtime Profile',
  'runtimeEngine.employeeRuntimePage': 'Employee Runtime',
  'runtimeEngine.employeeSectionTitle': 'Runtime Profile',
  'runtimeEngine.openRuntime': 'Runtime',
  'runtimeEngine.localOnly':
    'Stored in localStorage (ai-company-runtime-profiles) — no Ollama or cloud calls in V1.',
  'runtimeEngine.stats.totalProfiles': 'Runtime profiles',
  'runtimeEngine.connectionStatuses.mock': 'Mock (V1)',
  'runtimeOrchestrator.runPageTitle': 'Runtime Run',
  'runtimeOrchestrator.waitingApprovalNote':
    'Run paused at approval gate — mock Owner approval required before completion.',
  'runtimeOrchestrator.localOnly':
    'Stored in localStorage (ai-company-runtime-runs) — mock pipeline, no Ollama or provider calls.',
  'runtimeOrchestrator.contextTitle': 'Runtime context',
  'runtimeOrchestrator.pipelineSteps.run_model_router': 'Run Model Router',
  'runtimeOrchestrator.contextLayers.runtime_profile': 'Runtime profile',
  'memoryEngine.title': 'Employee Memory',
  'memoryEngine.pageTitle': '{name} — Memory',
  'memoryEngine.openMemory': 'Open Memory',
  'memoryEngine.localOnly':
    'Хранится в localStorage — без vector DB и подключённого Runtime.',
  'memoryEngine.searchHint': 'V1: только text match — semantic search в future.',
  'memoryEngine.summary.title': 'Memory Architecture',
  'memoryEngine.summary.modelIndependent':
    'Смена primaryModel с Claude на Qwen не переносит и не стирает этот memory store.',
  'memoryEngine.stats.withWorkspace': 'Workspace-linked',
  'competencyEngine.pageTitle': '{name} — Competencies',
  'competencyEngine.localOnly':
    'Хранится в localStorage — reputation считается локально, Runtime не подключён.',
  'competencyEngine.sections.reputation': 'Reputation',
  'competencyEngine.sections.learning': 'Learning Path',
  'competencyEngine.stats.trustScore': 'Trust score',
  'competencyEngine.meta.workspacePrefix': 'WS',
  'competencyEngine.reputation.trustScore': 'Trust score',
  'employeeProfile.sections.runtime': 'Runtime',
  'mock.lastActivity': 'Ожидание активации V1',
  'mock.relativeTime.now': 'сейчас',
  'mock.relativeTime.minutesAgo': '{minutes} мин назад',
  'mock.squads.orchestrator': 'Orchestrator',
  'mock.squads.memoryStore': 'Memory store',
  'mock.squads.toolGateway': 'Tool gateway',
  'mock.squads.coreEngineering': 'Core Engineering',
  'mock.squads.executive': 'Executive',
  'mock.squads.operations': 'Operations',
};
